version: '3.8'

services:
  face_recognition:
    build: .
    container_name: face_recognition_api
    ports:
      - "8000:8000"
    volumes:
      - ./database:/app/database
      - ./models:/app/models
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
      - MILVUS_HOST=standalone
      - MILVUS_PORT=19530
    networks:
      - milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  ngrok:
    image: ngrok/ngrok:latest  # Thêm thụt lề tại đây
    command: http face_recognition_api:8000
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    depends_on:
      - face_recognition
    networks:
      - milvus

networks:
  milvus:
    external: true
